package com.example.PadelCaleruela.model;

public enum NotificationType {

    FRIEND_REQUEST,
    FRIEND_ACCEPT,

    LEAGUE_INVITATION,
    LEAGUE_INVITATION_ACCEPT,       // 🔥 NUEVO
    LEAGUE_INVITATION_REJECT,       // 🔥 NUEVO

    MATCH_INVITATION,
    MATCH_INVITATION_ACCEPT,        // 🔥 NUEVO
    MATCH_INVITATION_REJECT,        // 🔥 NUEVO

    RESERVATION_CANCELLED,
    RESERVATION_TIME_CANCELLED,

    RESERVATION_PAYMENT_CONFIRMED,
    RESERVATION_PAYMENT_CANCELLED,
    RESERVATION_PLAYER_LEFT,

    LEAGUE_JOINED,
    LEAGUE_JOINED_WITH_YOU,
    LEAGUE_REJECTED,
    LEAGUE_DELETED,

    MATCH_INVITATION_ACCEPTED,
    MATCH_INVITATION_REJECTED,
    MATCH_JOINED_WITH_YOU,

    PUBLIC_MATCH_JOINED,            // 🔥 NUEVO (unirse a partida pública)
    MATCH_PLAYER_LEFT,            // 🔥 NUEVO (abandonar partida)

    ADMIN_USER_REGISTERED,
    ADMIN_LEAGUE_CREATED,
    ADMIN_LEAGUE_DELETED

    }
